config/routes.rb
Ohforgetfulme::Application.routes.draw do
  root :to => "reminds#new"
  resources :reminds, :only => [:new,:show, :create]
  get "check" => "reminds#check"











end

app/models/remind.rb

class Remind < ActiveRecord::Base
    validates :name , :presence => true
    validates :date, :presence => true
    validates :email, :presence => true

    def self.find_reminders_todo
        sent = 0
        Remind.all.each do |x|
            if Time.now >= x.date
                if x.done == nil
                    x.done = true
                    x.save 
                    ReminderMailer.reminder_email(x).deliver
                    sent += 1
                end
            end
        end  
        return sent
    end

    def self.welcome_email(passedRemind)
        found = false
        Remind.all.each do |table|
            if passedRemind.email == table.email
                found = true
            end
        end
        if found == false
            ReminderMailer.welcome_email(passedRemind).deliver
        end
        return found
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/reminds_controller.rb

class RemindsController < ApplicationController
  before_action :set_remind, only: [:show, :edit, :update, :destroy]

  # GET /reminds
  # GET /reminds.json
  def check
    # Remind.find_reminders_todo
    @sent = Remind.find_reminders_todo
  end

  # GET /reminds/1
  # GET /reminds/1.json
  def show
    if URI(request.referer).path == "/"
      print "From new"
    else
      redirect_to :action => "new"
    end
  end

  # GET /reminds/new
  def new
    @remind = Remind.new
  end

  # GET /reminds/1/edit


  # POST /reminds
  # POST /reminds.json
  def create
    @remind = Remind.new(remind_params)
    passer = @remind
    #Send welcome email if conditions pass
    Remind.welcome_email(passer)
    respond_to do |format|
      if @remind.save
      
        format.html { redirect_to @remind, notice: 'Reminder was successfully created.' }
        format.json { render action: 'show', status: :created, location: @remind }
      else
        format.html { render action: 'new' }
        format.json { render json: @remind.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reminds/1
  # PATCH/PUT /reminds/1.json
  def update
    respond_to do |format|
      if @remind.update(remind_params)
        format.html { redirect_to @remind, notice: 'Remind was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @remind.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reminds/1
  # DELETE /reminds/1.json
  def destroy
    @remind.destroy
    respond_to do |format|
      format.html { redirect_to reminds_url }
      format.json { head :no_content }
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_remind
      @remind = Remind.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def remind_params
      params.require(:remind).permit(:name, :date, :time,:email, :message, :done )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reminds_helper.rb
module RemindsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Oh Forgetful Me</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div id = "heading-span"></div>
    <div id = "container">
    <div id = "heading">
        <a href="/" class="link"><h1>OhForgetful.Me</h1>
        <h3>Remember important things</h3></a>
    </div>

<%= yield %>
<div id = "footer">
        This website was created by Matthew Hamilton
    </div>
</div>
</body>
</html>

app/views/reminds/_form.html.erb
<%= form_for(@remind) do |f| %>
  <% if @remind.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@remind.errors.count, "error") %> prohibited this remind from being saved:</h2>

      <ul>
      <% @remind.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    What would you like to remind yourself about? <br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    What date would you like the reminder on?<br>
    <%= f.date_select :date %>
<br><br>
    How would you like to be contacted? <br>
    
      <%= f.label :contactemail ,'Email Address' %><br>
      <%= f.text_field :email , :placeholder => "Chandra@OhForgetful.Me", :size => 25%>
    <br><br>
   
    <%= f.label "The message for future you:" %><br>
    <%= f.text_area :message %>
  </div>
</div>
  <div class="field">

  <div class="actions" align = "center">
    <br>
    <%= f.submit "   Set Reminder   ", :class=>"form-button"%>
  </div>
</div>
<% end %>

app/views/reminds/check.html.erb
<div class = "field">
<h1>Reminders Manually Sent</h1>
<h4>
<b><%= @sent.inspect %></b> reminder emails were sent.
</h4>
</div>

app/views/reminds/edit.html.erb
<h1>Editing remind</h1>

<%= render 'form' %>

<%= link_to 'Show', @remind %> |
<%= link_to 'Back', reminds_path %>

app/views/reminds/index.html.erb
<h1>Listing reminds</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Date</th>
      <th>Time</th>
      <th>Contactmethod</th>
      <th>Contactinfo</th>
      <th>Message</th>
      <th>Timecreated</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @reminds.each do |remind| %>
      <tr>
        <td><%= remind.name %></td>
        <td><%= remind.date %></td>
        <td><%= remind.time %></td>
        <td><%= remind.contactmethod %></td>
        <td><%= remind.contactinfo %></td>
        <td><%= remind.message %></td>
        <td><%= remind.timecreated %></td>
        <td><%= link_to 'Show', remind %></td>
        <td><%= link_to 'Edit', edit_remind_path(remind) %></td>
        <td><%= link_to 'Destroy', remind, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Remind', new_remind_path %>

app/views/reminds/new.html.erb
    <div id ="form">
        <%= render 'form' %>
    </div>
    

app/views/reminds/revision._form.html.erb
  <tr><td><%= f.check_box"contactemail"%></td><td><%= f.label :contactemail ,'Email' %></td>
    <td><%= f.text_field :emailaddress , :placeholder => "bigbtymama@OhForgetful.Me", :size => 25%></td></tr>
    
    <tr><td><%= f.check_box "contacttext"%></td><td><%= f.label :contacttext ,'Text' %></td>
      <td><%= f.text_field :textnumber, :size => 25 %></td></tr>

    <tr><td><%= f.check_box "contactphone"%></td><td><%= f.label :contactphone ,'Phone' %></td>
    <td><%= f.text_field :phonenumber, :size => 25 %></td></tr>

app/views/reminds/show.html.erb
<div class = "field">
<p id="notice" ><%= notice %></p>
<h2> New Reminder Created</h2>
<p>
  <h3>Name:
  <b><%= @remind.name %></b>
</h3>
</p>
<p>
  <strong>Date:</strong>
  <%= @remind.date %>
</p>

<p>
  <strong>Email:</strong>
  <%= @remind.email %>
</p>

<p>

<p>
  <strong>Message:</strong>
  <%= @remind.message %>
</p>


<%= link_to 'New', "/" %>
</div>